config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

from . import views

urlpatterns = [
    path('', views.index, name = 'index'),
    path('admin/', admin.site.urls),
    path('item/', include('item.urls')),
    path('mente/', include('mente.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

item/urls.py
from django.urls import path, include

from . import views

app_name = 'item'

urlpatterns = [
    path('top_page/', views.top_page, name = 'top_page'),
    path('test_check/', views.test_check, name = 'test_check'),
    path('prob_list/<int:shou_id>', views.prob_list, name = 'prob_list'),
    path('answer_page/<int:shou_id>/<int:prob_num>', views.answer_page, name = 'answer_page'),
]

mente/urls.py
from django.urls import path, include

from . import views

app_name = 'mente'

urlpatterns = [
    path('shou_registration', views.shou_registration, name = 'shou_registration'),
    path('registration/<int:shou_id>', views.registration, name = 'registration'),
    path('pre_registration', views.pre_registration, name = 'pre_registration'),
    path('pre_edit', views.pre_edit, name = 'pre_edit'),
    path('edit/<int:pk>/', views.Edit.as_view(), name='edit'),
    path('pre_delete', views.pre_delete, name = 'pre_delete'),
    path('delete/<int:pk>/', views.Delete.as_view(), name = 'delete'),
]

mente/models.py
from django.db import models

# Create your models here.

mente/forms.py
from django import forms
from item.models import Prob, Shou

class ProbForm(forms.ModelForm):
    class Meta:
        model = Prob
        fields = '__all__'

class ShouForm(forms.ModelForm):
    class Meta:
        model = Shou
        fields = '__all__'

mente/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views import View
from django.contrib.auth.models import User
from item.models import Shou, Prob, Shintyoku
from django.urls import reverse, reverse_lazy
from mente.forms import ProbForm, ShouForm
from django.views.generic import UpdateView, DeleteView
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin

class Shou_Registration(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        form = ShouForm()
        context = {'form':form}

        return render(request, 'mente/shou_registration.html', context=context)

    def post(self, request, *args, **kwargs):
        form = ShouForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(reverse('item:top_page'))
        else:
            return render(request, 'mente/shou_registration.html', {'form':form})

shou_registration = Shou_Registration.as_view()

class Pre_Registration(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):

        form_ = Shou.objects.all()
        form = []
        for i in range(len(form_)):
            form__ = [i+1, form_[i].shou_name, form_[i].id]
            form.append(form__)
        print(form)
        context = {'form':form}

        return render(request, 'mente/pre_registration.html', context=context)

pre_registration = Pre_Registration.as_view()


class Registration(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        shou_id = int(kwargs['shou_id'])

        try:
            last_num = Prob.objects.filter(shou_id=shou_id).order_by('-prob_num')[0].prob_num
        except:
            last_num = 0

        form = ProbForm(initial={"shou_id":Shou.objects.get(id=shou_id).id, "prob_num":last_num+1})
        context = {'form':form, 'shou_id':shou_id}
        return render(request, 'mente/registration.html', context=context)

    def post(self, request, *args, **kwargs):
        shou_id = int(kwargs['shou_id'])
        form = ProbForm(request.POST)

        if form.is_valid():
            form.save()
            return redirect(reverse('mente:pre_registration'))
        else:
            return render(request, 'mente/registration.html', {'form':form})



registration = Registration.as_view()


class Pre_edit(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        probs = Prob.objects.all().order_by('prob_num').order_by('shou_id')

        shou_num = probs

        forms = []
        for prob in probs:
            forms.append( [ prob, int((prob.shou_id - 2)/10) ] )

        context = {'forms':forms}

        return render(request, 'mente/pre_edit.html', context=context)

pre_edit = Pre_edit.as_view()

class Edit(LoginRequiredMixin, UpdateView):
    model = Prob
    form_class = ProbForm
    template_name = 'mente/edit.html'
    success_url = reverse_lazy('mente:pre_edit')

class Pre_delete(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        probs = Prob.objects.all().order_by('prob_num').order_by('shou_id')
        context = {'probs':probs}

        forms = []
        for prob in probs:
            forms.append( [ prob, int((prob.shou_id - 2)/10) ] )

        context = {'forms':forms}

        return render(request, 'mente/pre_delete.html', context=context)

pre_delete = Pre_delete.as_view()


class Delete(LoginRequiredMixin, DeleteView):
    model = Prob
    form_class = ProbForm
    template_name = 'mente/delete.html'
    success_url = reverse_lazy('mente:pre_delete')

templates/mente/delete.html
{% extends 'base_html.html' %}

{% block contents %}

<h2>問題削除ページ</h2>


<form method="post">

<table>
  <tr>
    <th class="delete1">章タイトル：</th><th class = "delete2">{{object.shou.shou_name}}</th>
  </tr>
  <tr>
    <th class="delete1">問題タイトル：</th><th class = "delete2">{{object.title}}</th>
  </tr>
  <tr>
    <th class="delete1">問題文：</th><th class = "delete2">{{object.prob_bun}}</th>
  </tr>
</table>

<h3>上記の問題を<font color="red">「削除」</font>しますか？</h3>

<button type="submit" name="登録" value="登録" onclick="check()">削除する</button>

  {% csrf_token %}
</form>


{% endblock %}

templates/mente/edit.html
{% extends 'base_html.html' %}

{% block contents %}

<h2>問題編集ページ</h2>


<form method="post">

<table>
  {{form}}
</table>


<button type="submit" name="登録" value="登録" onclick="check()">保存</button>

  {% csrf_token %}
</form>


{% endblock %}

templates/mente/pre_delete.html
{% extends 'base_html.html' %}

{% block contents %}

<h2>問題削除ページ</h2>
<h3>削除したい問題を選択して下さい</h3>


<table>

  <tr>
    <th>章番号</th>
    <th>問題番号</th>
    <th>問題タイトル</th>
  </tr>

  {% for form in forms %}
  <tr>
    <th>{{form.1}}</th>
    <th>{{form.0.prob_num}}</th>
    <th style="text-align:left; padding-left:20px;"><a href={% url "mente:delete" pk=form.0.id %}>{{form.0.title}}</a></th>
  </tr>
  {% endfor %}

</table>


{% endblock %}

templates/mente/pre_edit.html
{% extends 'base_html.html' %}

{% block contents %}

<h2>問題編集ページ</h2>
<h3>編集したい問題を選択して下さい</h3>


<table>

  <tr>
    <th>章番号</th>
    <th>問題番号</th>
    <th>問題タイトル</th>
  </tr>

  {% for form in forms %}
  <tr>
    <th>{{form.1}}</th>
    <th>{{form.0.prob_num}}</th>
    <th style="text-align:left; padding-left:20px;"><a href={% url "mente:edit" pk=form.0.id %}>{{form.0.title}}</a></th>
  </tr>
  {% endfor %}

</table>


{% endblock %}

templates/mente/pre_registration.html
{% extends 'base_html.html' %}

{% block contents %}

<h2>問題登録ページ</h2>



{% csrf_token %}

<table>
<tr>
  <th>章番号</th>
  <th>章タイトル</th>
</tr>

{% for form_ in form %}
<tr>
  <th style="text-align:center;">{{form_.0}}</th>
  <th style="text-align:left; padding-left:20px;">
    <a href={% url "mente:registration" shou_id=form_.2 %}>{{form_.1}}</a>
  </th>
</tr>
{% endfor %}
</table>


{% endblock %}

templates/mente/registration.html
{% extends 'base_html.html' %}

{% block contents %}

<h2>問題登録ページ</h2>


<form action="{% url 'mente:registration' shou_id=shou_id %}" method="post">

{% csrf_token %}
<table>

<!--
  <tr>
    <th>問題タイトル</th><td>{{form.title}}</td>
  </tr>
  <tr>
    <th>問題文</th><td>{{form.prob_bun}}</td>
  </tr>
  <tr>
    <th>選択肢１</th><td>{{form.sentaku_1}}</td>
  </tr>
  <tr>
    <th>選択肢２</th><td>{{form.sentaku_2}}</td>
  </tr>
  <tr>
    <th>選択肢３</th><td>{{form.sentaku_3}}</td>
  </tr>
  <tr>
    <th>選択肢４</th><td>{{form.sentaku_4}}</td>
  </tr>
  <tr>
    <th>正解番号</th><td>{{form.seikai}}</td>
  </tr>
  <tr>
    <th>解説</th><td>{{form.kaisetsu}}</td>
  </tr>

-->

{{form}}

</table>
<button type="submit" name="登録" value="登録" onclick="check()">登録</button>

</form>


{% endblock %}

templates/mente/shou_registration.html
{% extends 'base_html.html' %}

{% block contents %}

<h2>章登録ページ</h2>


<form action="{% url 'mente:shou_registration' %}" method="post">

{% csrf_token %}
<table>

{{form}}

</table>
<button type="submit" name="登録" value="登録" onclick="check()">登録</button>

</form>


{% endblock %}