config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

from . import views

urlpatterns = [
    path('', views.index, name = 'index'),
    path('admin/', admin.site.urls),
    path('item/', include('item.urls')),
    path('mente/', include('mente.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

item/urls.py
from django.urls import path, include

from . import views

app_name = 'item'

urlpatterns = [
    path('top_page/', views.top_page, name = 'top_page'),
    path('test_check/', views.test_check, name = 'test_check'),
    path('prob_list/<int:shou_id>', views.prob_list, name = 'prob_list'),
    path('answer_page/<int:shou_id>/<int:prob_num>', views.answer_page, name = 'answer_page'),
]

mente/urls.py
from django.urls import path, include

from . import views

app_name = 'mente'

urlpatterns = [
    path('shou_registration', views.shou_registration, name = 'shou_registration'),
    path('registration/<int:shou_id>', views.registration, name = 'registration'),
    path('pre_registration', views.pre_registration, name = 'pre_registration'),
    path('pre_edit', views.pre_edit, name = 'pre_edit'),
    path('edit/<int:pk>/', views.Edit.as_view(), name='edit'),
    path('pre_delete', views.pre_delete, name = 'pre_delete'),
    path('delete/<int:pk>/', views.Delete.as_view(), name = 'delete'),
]

templates/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <p>共通表示する部分</p>

    {% block contents %}

    {% endblock %}

  </body>
</html>

templates/base_html.html
<!DOCTYPE html>
<html lang="ja">
  <head>
    {% load static %}
    <meta charset="utf-8">
    <title>学習サイト</title>
    <link rel="stylesheet" type="text/css" href= {% static "css/style.css" %}>
  </head>
  <body>
    <header id="header">
      <nav>
          <a class="logo" href={% url "item:top_page" %}>
            <img src="https://www.kikagaku.co.jp/wp-content/themes/kikagaku_hp_20180831-7/src/img/logo_black.png">
          </a>
          <ul>
        {% if user.is_authenticated %}
        {% if user.auth_view %}
            <li>
              <a href="/admin">
                <img class="active" src={% static "images/item/icon_setting-active.svg" %}>
                <img class="inactive" src={% static "images/item/icon_setting.svg" %}>
                管理サイト
              </a>
            </li>
        {% endif %}
        {% endif %}
        {% if user.is_authenticated %}
            <li>
              <a href="/accounts/logout">
                <img class="active" src="https://aiacademy.jp/assets/images/icon_mypage-active.svg">
                <img class="inactive" src="https://aiacademy.jp/assets/images/icon_mypage.svg">
                {{ user.username }}さんログアウト
              </a>
            </li>
            {% endif %}
          </ul>
      </nav>
    </header>

    <div class="flex">
      <div class="sidebar">
        {% if user.is_authenticated %}
        <ul class = "nab" style="text-align:left;">
          <li><a href = {% url "item:top_page" %}>マイページ</a></li>
          {% if user.auth_view %}
          <li><a href = {% url "item:test_check" %}>テスト結果確認</a></li>
          {% if user.auth_edit %}
          <li><a href = {% url "mente:shou_registration" %}>章登録ページ</a></li>
          <li><a href = {% url "mente:pre_registration" %}>問題登録ページ</a></li>
          <li><a href = {% url "mente:pre_edit" %}>問題編集ページ</a></li>
          <li><a href = {% url "mente:pre_delete" %}>問題削除ページ</a></li>
          {% endif %}
          {% endif %}
        </ul>
        {% endif %}
      </div>

      <div class = "main-container">
        <div class = "contents">
          {% block contents %}

          {% endblock %}
        </div>
      </div>
    </div>

  </body>
</html>