config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

from . import views

urlpatterns = [
    path('', views.index, name = 'index'),
    path('admin/', admin.site.urls),
    path('item/', include('item.urls')),
    path('mente/', include('mente.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

item/urls.py
from django.urls import path, include

from . import views

app_name = 'item'

urlpatterns = [
    path('top_page/', views.top_page, name = 'top_page'),
    path('test_check/', views.test_check, name = 'test_check'),
    path('prob_list/<int:shou_id>', views.prob_list, name = 'prob_list'),
    path('answer_page/<int:shou_id>/<int:prob_num>', views.answer_page, name = 'answer_page'),
]

item/models.py
from django.db import models
from django.contrib.auth.models import User
from accounts.models import CustomUser
from django import forms

# 会員マスタ
class Kaiin(models.Model):
    class Meta:
        db_table = 'kaiin'

    name = models.CharField('会員名', max_length=255, null=True, blank=True)
    login_pass = models.CharField('ログインPass', max_length=255, null=True, blank=True)


# 章マスタ
class Shou(models.Model):
    class Meta:
        db_table = 'shou'

    shou_name = models.CharField('章名', max_length=255, null=True, blank=True)

# 問題マスタ
class Prob(models.Model):
    class Meta:
        db_table = 'prob'

    shou = models.ForeignKey(Shou, verbose_name='章番号',  on_delete=models.CASCADE)
    prob_num = models.IntegerField(verbose_name='問題番号', null=True, blank=True)
    title = models.CharField('問題タイトル', max_length=255, null=True, blank=True)
    prob_bun = models.CharField('問題文', max_length=5000, null=True, blank=True)
    sentaku_1 = models.CharField('選択肢１', max_length=255, null=True, blank=True)
    sentaku_2 = models.CharField('選択肢２', max_length=255, null=True, blank=True)
    sentaku_3 = models.CharField('選択肢３', max_length=255, null=True, blank=True)
    sentaku_4 = models.CharField('選択肢４', max_length=255, null=True, blank=True)
    seikai = models.IntegerField('正解番号', null=True, blank=True)
    kaisetsu = models.CharField('解説', max_length=5000, null=True, blank=True)

# 学習進捗
class Shintyoku(models.Model):
    class Meta:
        db_table = 'shintyoku'

    kaiin = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    shou = models.ForeignKey(Shou, on_delete=models.CASCADE)
    prob = models.ForeignKey(Prob, on_delete=models.CASCADE)
    seigo = models.CharField('正誤', max_length=255)
    answer_date = models.DateField('最終回答日', null=True, blank=True)

item/forms.py
from django import forms

item/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views import View
from django.contrib.auth.models import User
from item.models import Shou, Prob, Shintyoku, CustomUser
from django.urls import reverse
import datetime
from django.contrib.auth.mixins import LoginRequiredMixin


class Top_page(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        user_id = request.user.id
        user_name = request.user.get_username
        shou_kensu = Shou.objects.filter().count()
        shou_name = Shou.objects.all()
        shou_num = int(Shou.objects.all()[0].id)

        mondai_kensu = []
        for i in range(shou_kensu):
            kensu_ = Prob.objects.filter(shou_id=shou_num).count()
            mondai_kensu.append(kensu_)
            shintyoku_kensu = []
            shintyoku_ritsu = []
            seikai_ritsu = []
            shou_num += 10

        shou_num = int(Shou.objects.all()[0].id)
        for i in range(shou_kensu):
            kensu_ = Shintyoku.objects.filter(kaiin_id=user_id, shou_id=shou_num).count()
            shintyoku_kensu.append(kensu_)

            if mondai_kensu[i] != 0:
                shintyoku_ritsu.append(int(round(shintyoku_kensu[i]/mondai_kensu[i],2)*100))
            else:
                shintyoku_ritsu.append(0)

            正解数 = Shintyoku.objects.filter(kaiin_id=user_id, shou_id=shou_num, seigo='正解').count()
            不正解数 = Shintyoku.objects.filter(kaiin_id=user_id, shou_id=shou_num, seigo='不正解').count()

            try:
                seikai_ritsu_ = 正解数/(正解数 + 不正解数)
                seikai_ritsu.append(int(round(seikai_ritsu_*100,2)))
            except:
                if 不正解数 == 0:
                    if 正解数 == 0:
                        seikai_ritsu.append(0)
                    else:
                        seikai_ritsu.append(100)

            shou_num += 10

        ritsu = []
        shou_num = int(Shou.objects.all()[0].id)
        for i in range(len(seikai_ritsu)):
            ritsu_ = []
            ritsu_.append(shou_num)
            ritsu_.append(i + 1)
            ritsu_.append(shou_name[i].shou_name)
            ritsu_.append(shintyoku_ritsu[i])
            ritsu_.append(seikai_ritsu[i])
            ritsu.append(ritsu_)
            shou_num += 10

        context = {'user_id':user_id, 'user_name':user_name,\
                'shintyoku_ritsu':shintyoku_ritsu, 'seikai_ritsu':seikai_ritsu, 'ritsu':ritsu}

        return render(request, 'item/top_page.html', context=context)

top_page = Top_page.as_view()

class Prob_list(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        shou_id_ = kwargs['shou_id']
        user_id = request.user.id
        probs = Prob.objects.filter(shou_id=shou_id_)
        # FreignFieldが指定されているTableとのJoin句
        shintyokus = Shintyoku.objects.filter(kaiin_id=user_id, shou_id=shou_id_).select_related()

        statuses = []
        for prob in probs:
            prob_num = prob.prob_num
            prob_title = prob.title
            i = 0
            for shintyoku in shintyokus:
                if prob_num == shintyoku.prob.prob_num:
                    prob_status = shintyoku.seigo
                    i += 1

            if i == 0:
                statuses.append({'prob_num':prob_num, 'prob_title':prob_title, 'prob_status':'未回答'})
            else:
                statuses.append({'prob_num':prob_num, 'prob_title':prob_title, 'prob_status':prob_status})


        shou_name = Shou.objects.filter(id = shou_id_)[0].shou_name


        context = {'statuses':statuses, 'shou_id_':shou_id_, 'shou_id':int((shou_id_ - 2)/10), 'shou_name':shou_name}
        return render(request, 'item/prob_list.html', context=context)

prob_list = Prob_list.as_view()

class Answer_page(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        shou_id_ = kwargs['shou_id']
        prob_num = kwargs['prob_num']
        try:
            prob_ = Prob.objects.filter(shou_id=shou_id_, prob_num=prob_num)[0]
            context = {'prob_':prob_, 'prob_num':prob_num, 'shou_id':shou_id_}
            return render(request, 'item/answer_page.html', context=context)
        except:
            shou_id_max = Shou.objects.all().order_by('-id')[0].id
            if shou_id_ != shou_id_max:
                shou_id_ = shou_id_ + 10
                prob_num = 1
                return redirect(reverse('item:answer_page', args=[shou_id_ ,prob_num]))
            else:
                shou_id_ = Shou.objects.all().order_by('id')[0].id
                prob_num = 1
                return redirect(reverse('item:answer_page', args=[shou_id_ ,prob_num]))


    def post(self, request, *args, **kwargs):
        answer = int(request.POST.getlist('選択肢')[0])
        shou_id = kwargs['shou_id']
        prob_num = int(kwargs['prob_num'])
        next_id = prob_num + 1
        prob = Prob.objects.filter(shou_id=shou_id, prob_num=prob_num)[0]
        true_ = prob.seikai
        if true_ == answer:
            seigo = '正解'
        else:
            seigo = '不正解'

        shou_id = Prob.objects.filter(shou_id= shou_id, prob_num=prob_num).select_related()[0].shou_id
        prob_id = Prob.objects.filter(shou_id= shou_id, prob_num=prob_num)[0].id

        try:
            id = Shintyoku.objects.filter(prob_id=prob_id, shou_id=shou_id, kaiin_id=request.user.id).select_related()[0].id
            query_ = Shintyoku.objects.get(id=id)
            query_.seigo = seigo
            query_.save()
        except:
            query_ = Shintyoku(seigo=seigo, answer_date=datetime.date.today(), kaiin_id=request.user.id, prob_id=prob_id, shou_id=shou_id)
            query_.save()

        context = {'answer':answer,'shou_id':shou_id, 'prob_num':prob_num, 'prob':prob, 'seigo':seigo, 'next_id':next_id, 'true_':true_}

        return render(request, 'item/answer_check.html', context=context)

answer_page = Answer_page.as_view()

class Test_check(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        corp_id = request.user.corp_id
        user_lists = CustomUser.objects.filter(corp_id=corp_id)
        contexts_ = []

        for user_list in user_lists:
            user_name = user_list.first_name
            user_id = user_list.id
            正解数 = Shintyoku.objects.filter(kaiin_id=user_id, seigo='正解').count()
            不正解数 = Shintyoku.objects.filter(kaiin_id=user_id, seigo='不正解').count()

            if (正解数 + 不正解数) != 0:
                score = str(int(100 * 正解数 / (正解数 + 不正解数))) + '点'
            else:
                score = "テスト未実施"
            contexts_.append({'user_name':user_name, 'score':score})

        context = {'contexts_':contexts_}

        return render(request, 'item/test_check.html', context=context)

test_check = Test_check.as_view()

templates/item/answer_check.html
{% extends 'base_html.html' %}

{% block contents %}


<table>
  <tr>
    <th style="font-size:20px;">　正誤：</th>
    <td><p>{{seigo}}</p></td>
  </tr>

  <tr>
    <th style="font-size:20px;">　問題：</th>
    <td><p>{{prob.prob_bun}}</p></td>
  </tr>

  <tr>
    <th style="font-size:20px;"><span>　解説：</span></th>
    <td><p>{{ prob.kaisetsu| linebreaksbr }}</p></td>
  </tr>

  <tr>
    <th style="font-size:20px;">選択肢：</th>
    <td><p>{{answer}}番</p></td>
  </tr>
</table>

<table>
  <tr>
    <td style="padding:0 5px 0 5px;"><a href={% url "item:answer_page" shou_id=shou_id prob_num=prob_num %}>もう一度</a></td>
    <td style="padding:0 5px 0 5px;"><a href={% url "item:answer_page" shou_id=shou_id prob_num=next_id %}>次へ</a></td>
    <td style="padding:0 5px 0 5px;"><a href={% url "item:prob_list" prob.shou_id %}>問題一覧へ</a></td>
  </tr>
</table>

{% endblock %}

templates/item/answer_page.html
{% extends 'base_html.html' %}

{% block contents %}

<table>

<tr>
  <th style="font-size:20px;">タイトル：</th>
  <td><p>{{prob_.title}}</p></td>
</tr>

<tr>
  <th style="font-size:20px;">　問題文：</th>
  <td><p>{{prob_.prob_bun}}</p></td>
</tr>

<form action='/item/answer_page/{{shou_id}}/{{prob_num}}' method="post">
<tr>
  <th style="font-size:20px;">　選択肢：</th>
  <td>
    <input type="radio" name="選択肢" value=1>{{prob_.sentaku_1}}</input>
  </td>
</tr>

<tr>
  <th></th>
  <td>
    <input type="radio" name="選択肢" value=2>{{prob_.sentaku_2}}</input>
  </td>
</tr>

<tr>
  <th></th>
  <td>
    <input type="radio" name="選択肢" value=3>{{prob_.sentaku_3}}</input>
  </td>
</tr>

<tr>
  <th></th>
  <td>
    <input type="radio" name="選択肢" value=4>{{prob_.sentaku_4}}</input>
  </td>
</tr>

<tr>
  {% csrf_token %}
  <th></th>
  <td>
    <p><input type="submit" value="回答する"></p>
  </td>
</tr>
</form>

</table>



{% endblock %}

templates/item/prob_list.html
{% extends 'base_html.html' %}

{% block contents %}

<h2>第{{shou_id}}章：{{shou_name}}</h2>

<table>
  <tr>
    <th>問題番号</th>
    <th>タイトル</th>
    <th>ステータス</th>
  </tr>
{% for status in statuses %}
  <tr>
    <th>{{status.prob_num}}</th>
    <th style="text-align:left; padding-left:20px;">
      <a href= {% url "item:answer_page" shou_id=shou_id_ prob_num=status.prob_num %}> {{status.prob_title}} </a>
    </th>
    <th>{{status.prob_status}}</th>
  </tr>
{% endfor %}
</table>

{% endblock %}

templates/item/sample_item.html
{% extends 'base.html' %}

{% block contents %}

    <p>item_サンプルですよー！</p>

    {% for item in items %}
    <p>ID：{{item.id}}、名称：{{item.name}}、価格{{item.price}}</p>
    {% endfor %}

{% endblock %}

templates/item/sample_post.html
{% extends 'base.html' %}

{% block contents %}

    <p>入力画面</p>

    <form action="{% url 'item:sample_post' %}" method="post">
      {% csrf_token %}

      {% for form_ in form %}

      <ul>
      {{form_}}
      </ul>


      {% endfor %}

      <button type="submit" name="登録" value="登録" onclick="check()">


    </form>
{% endblock %}

templates/item/test_check.html
{% extends 'base_html.html' %}

{% block contents %}

<h2>テスト結果：{{user.corp}}様</h2>

<table style="width:30%;">
  <tr>
    <th>お名前</th>
    <th>正解率</th>
  </tr>
{% for context_ in contexts_ %}
  <tr style='text-align:center;'>
    <td>{{context_.user_name}} 様</td>
    <td>{{context_.score}}</td>
  </tr>
{% endfor %}
</table>

{% endblock %}

templates/item/top_page - コピー.html
{% extends 'base_html.html' %}

{% block contents %}

<h2>ようこそ、企業名：{{user.corp}}、ユーザーID：{{user.id}}の「{{user.username}}」さん</h2>
<h2>学習進捗</h2>

<table clas="inline-block">
</table>

<table clas="inline-block">
</table>

<table>
<tr>
  <td>
    <table class="table-two">
      <tr>
        <th></th>
        <th>回答率</th>
        <th>正解率</th>
      </tr>
      <tr>
        <td><p><a href={% url "item:prob_list" 1 %}>１章</a></p></td>
        <td>{{shintyoku_ritsu.0}}％</td>
        <td>{{seikai_ritsu.0}}％</td>
      </tr>

      <tr>
        <td><p><a href={% url "item:prob_list" 2 %}>２章</a></p></td>
        <td>{{shintyoku_ritsu.1}}％</td>
        <td>{{seikai_ritsu.1}}％</td>
      </tr>

      <tr>
        <td><p><a href={% url "item:prob_list" 3 %}>３章</a></p></td>
        <td>{{shintyoku_ritsu.2}}％</td>
        <td>{{seikai_ritsu.2}}％</td>
      </tr>

    </table>
  </td>
  <td>
    <table class="table-two">
        <tr>
          <th></th>
          <th>回答率</th>
          <th>正解率</th>
        </tr>
        <tr>
          <td><p><a href={% url "item:prob_list" 4 %}>４章</a></p></td>
          <td>{{shintyoku_ritsu.3}}％</td>
          <td>{{seikai_ritsu.3}}％</td>
        </tr>

        <tr>
          <td><p><a href={% url "item:prob_list" 5 %}>５章</a></p></td>
          <td>{{shintyoku_ritsu.4}}％</td>
          <td>{{seikai_ritsu.4}}％</td>
        </tr>

        <tr>
          <td><p><a href={% url "item:prob_list" 6 %}>６章</a></p></td>
          <td>{{shintyoku_ritsu.5}}％</td>
          <td>{{seikai_ritsu.5}}％</td>
        </tr>
    </table>
  </td>
</tr>
</table>

{% endblock %}

templates/item/top_page.html
{% extends 'base_html.html' %}

{% block contents %}

<h2>{{user.corp}} {{user.first_name}}様 マイページ</h2>
<h2>【学習進捗】</h2>

<table clas="inline-block">
</table>

<table clas="inline-block">
</table>

<table>
<tr>
  <td>
    <table class="table-two">
      <tr>
        <th>章タイトル</th>
        <th>回答率</th>
        <th>正解率</th>
      </tr>
      {% for ritsu_ in ritsu %}
      <tr>
        <td><p><a href={% url "item:prob_list" ritsu_.0 %}>{{ritsu_.1}}章：{{ritsu_.2}}</a></p></td>
        <td>{{ritsu_.3}}％</td>
        <td>{{ritsu_.4}}％</td>
      </tr>
      {% endfor %}
    </table>
  </td>
</tr>
</table>

{% endblock %}